### PR TITLE
fix: Various Nuxt Upgrade Issues

### LINKED ISSUE #5543: [BUG] - Mealie nightly visual glitches with Nuxt 3 upgrade
I downloaded the latest nightly and found some visual glitches related to Nuxt 3 migration.

1. Admin settings navigation pane doesn't update, so can't actually navigate to any settings
    Image

2. Shopping lists "back button" is too small for the text on my iPhone
    image

3. The old font doesn't seem to be working. I see a 404 when trying to fetch the Roboto font

### PR DESCRIPTION
**Pull request by michael-genson**
## What this PR does / why we need it:

_(REQUIRED)_

Fixes a few various issues reported in https://github.com/mealie-recipes/mealie/issues/5543. The issue with the site settings page doesn't make any sense but this fix works so whatever.

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes https://github.com/mealie-recipes/mealie/issues/5543

## Special notes for your reviewer:

_(fill-in or delete this section)_

Also fixed a couple issues with cookbooks rendering on the sidebar.

## Testing

Manually built the prod image locally and everything seems to work as expected.

### CODE REVIEW

File: frontend/pages/shopping-lists/[id].vue [hunk 1]
```diff
@@ -41,7 +41,9 @@
         <v-container>
           <v-row>
             <v-col
-              cols="3"
+              cols="12"
+              sm="4"
+              md="3"
```
Comment (Kuchenpirat) [inline frontend/pages/shopping-lists/[id].vue:46]: all of those are unnecessairy
```suggestion
```

**Review by boc-the-git — APPROVED** [review]
LGTM

File: frontend/pages/shopping-lists/[id].vue [hunk 2]
```diff
@@ -51,8 +53,10 @@
               />
             </v-col>
             <v-col
-              cols="6"
-              class="d-none d-lg-flex justify-center"
+              cols="12"
+              sm="4"
+              md="6"
```
Comment (Kuchenpirat) [inline frontend/pages/shopping-lists/[id].vue:58]: all of this can be done a lot simpler and the elements will be still in the same row. 
we can just add an `v-if="smAndUp" to the image column and add `    const { smAndUp } = useDisplay();` to the script and return it to the tempalte

```suggestion
              cols="12"
              sm="4"
              md="6"
```

**Comment by Kuchenpirat** [comment]
welp was a few seconds to late then :D

**Comment by boc-the-git** [comment]
> welp was a few seconds to late then :D

:sweat_smile: 

If you raise a PR I can tick it :+1:

**Comment by Kuchenpirat** [comment]
@boc-the-git 
- #5547
